# Bluetooth-Name (Maximal 16 Zeichen!)
CONFIG_ZMK_KEYBOARD_NAME="Barsch"
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
# Studio aktivieren (GUI-Support)
# CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# USB-Schnittstelle radikal bereinigen
# (Verhindert, dass fehlerhafte serielle Treiber die Tastatur blockieren)
CONFIG_ZMK_USB_LOGGING=n
CONFIG_USB_CDC_ACM=n

# Batteriestatus-Reporting (für das Betriebssystem)
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# RGB-Energiesparmodus
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
# Maximale Helligkeit beim Start (0-255)
# Automatisch ausschalten, wenn die Tastatur in den Idle-Modus geht
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

